about.name=${project.name}
about.version=${project.version}
about.description=${project.description}
about.copyright=${project.inceptionYear} SUPSI Memet Emre Yildirim, Niccolo Xhyra
about.buildDate=${maven.build.timestamp}